#!/usr/bin/env python3
"""Generate SYNTHETIC master files that exercise analysis/run_all.R (register R-028 pairing item, contract item 10).

Everything written here is invented. Every study_id starts with synth_, every provenance field is an obviously synthetic
value (DOI prefix 10.0000/synthetic..., extractor synthetic-generator, URL https://synthetic.invalid/...). The files live
under analysis/synthetic/ so they never enter extraction/. Standard library only; deterministic (seeded).

Outputs (next to this script):
  master_dryrun.csv            five abilities, k = 1 each: rct SMD pair (A14), pre_post with pre_post_r blank (A16),
                               crossover with pre_post_r 0.6 (A02), prevalence_survey PLO (A21), case_report n = 1 (A03)
  master_pooling.csv           A03 k = 5 rct (+ one non-primary outcome row pair, + one SE-reported pair);
                               A07 k = 4 pre_post with two blank pre_post_r; A21 PLO k = 3; A05 k = 12 rct (Egger/funnel)
  population_sd_synthetic.csv  one verified row (A03 axillary temperature, degC) so Z is exercised, one pilot_unverified
  grade_final_synthetic.csv    contract item 6 header; one row per pooling ability (A03, A07, A21, A05), signed=no
Usage: python3 analysis/synthetic/make_synthetic_master.py
"""
import csv, os, random

HERE = os.path.dirname(os.path.abspath(__file__))
random.seed(20261004)

HEADER = ("study_id,record_id,ability_id,design,population,n_total,condition_label,n_condition,comparator_label,lever_type,"
          "outcome_measure,instrument,unit,timepoint,stat_type,value,dispersion_type,dispersion_value,ci_low,ci_high,p_value,"
          "baseline_value,baseline_dispersion,n_responders,n_tested,pre_post_r,is_primary_outcome,value_source,derivation,"
          "source_doi,source_url,location,verbatim_anchor,extractor_id,extraction_date,verification_route,skill_version,model,notes").split(",")

GRADE_HEADER = ("ability_id,outcome,n_studies,n_participants,design_mix,starting_level,rob_downgrade,inconsistency_downgrade,"
                "indirectness_downgrade,imprecision_downgrade,publication_bias_downgrade,large_effect_upgrade,dose_response_upgrade,"
                "opposing_confounding_upgrade,draft_certainty,reasons,plain_language_statement,rater_id,date,skill_version,model,"
                "final_certainty,final_rater_id,final_date,change_reason,signed").split(",")

POP_HEADER = "ability_id,variable,mean,sd,unit,population,n,source_doi,source_citation,location,status,notes".split(",")


def prov(study, k):
    """Obviously synthetic provenance block."""
    return dict(source_doi=f"10.0000/synthetic.{study}", source_url=f"https://synthetic.invalid/{study}",
                location=f"SYNTHETIC p. {k}, Table S", verbatim_anchor="SYNTHETIC anchor text not from any paper",
                extractor_id="synthetic-generator", extraction_date="2026-10-04", verification_route="pdf_full_text",
                skill_version="synthetic0", model="synthetic-model-string",
                notes="SYNTHETIC ROW generated by analysis/synthetic/make_synthetic_master.py; not evidence")


def row(**kw):
    r = {h: "" for h in HEADER}
    r.update(kw)
    return r


def rct_pair(study, record, ability, outcome, unit, lever, mean_i, sd_i, n_i, mean_c, sd_c, n_c, primary="yes",
             disp="SD", timepoint="end of training", population="synthetic adults"):
    base = dict(study_id=study, record_id=record, ability_id=ability, design="rct", population=population,
                n_total=n_i + n_c, lever_type=lever, outcome_measure=outcome, instrument="synthetic device", unit=unit,
                timepoint=timepoint, stat_type="mean", is_primary_outcome=primary, value_source="table", **prov(study, 1))
    if disp == "SE":
        d_i, d_c = round(sd_i / n_i ** 0.5, 3), round(sd_c / n_c ** 0.5, 3)
    else:
        d_i, d_c = sd_i, sd_c
    return [row(**base, condition_label="intervention", n_condition=n_i, comparator_label="control", value=mean_i,
                dispersion_type=disp, dispersion_value=d_i),
            row(**base, condition_label="control", n_condition=n_c, comparator_label="", value=mean_c,
                dispersion_type=disp, dispersion_value=d_c)]


def pre_post_row(study, record, ability, outcome, unit, lever, post, pre, sd_pre, n, r="", design="pre_post",
                 primary="yes", timepoint="end of 4 weeks"):
    return [row(study_id=study, record_id=record, ability_id=ability, design=design, population="synthetic adults",
                n_total=n, condition_label="intervention", n_condition=n, comparator_label="", lever_type=lever,
                outcome_measure=outcome, instrument="synthetic device", unit=unit, timepoint=timepoint, stat_type="mean",
                value=post, dispersion_type="SD", dispersion_value=round(sd_pre * 1.05, 2), baseline_value=pre,
                baseline_dispersion=sd_pre, pre_post_r=r, is_primary_outcome=primary, value_source="text", **prov(study, 2))]


def crossover_pair(study, record, ability, outcome, unit, lever, mean_i, sd_i, mean_s, sd_s, n, r):
    base = dict(study_id=study, record_id=record, ability_id=ability, design="crossover", population="synthetic adults",
                n_total=n, lever_type=lever, outcome_measure=outcome, instrument="synthetic thermistor", unit=unit,
                timepoint="during session", stat_type="mean", is_primary_outcome="yes", value_source="figure",
                **prov(study, 3))
    return [row(**base, condition_label="intervention", n_condition=n, comparator_label="sham", value=mean_i,
                dispersion_type="SD", dispersion_value=sd_i, pre_post_r=r),
            row(**base, condition_label="sham", n_condition=n, comparator_label="", value=mean_s, dispersion_type="SD",
                dispersion_value=sd_s)]


def prevalence_row(study, record, ability, outcome, x, n):
    return [row(study_id=study, record_id=record, ability_id=ability, design="prevalence_survey",
                population="synthetic survey sample", n_total=n, condition_label="whole sample", n_condition=n,
                lever_type="none", outcome_measure=outcome, instrument="synthetic questionnaire", unit="proportion",
                timepoint="single survey", stat_type="count", dispersion_type="none", n_responders=x, n_tested=n, is_primary_outcome="yes",
                value_source="text", **prov(study, 4))]


def case_report_row(study, record, ability, outcome, unit, lever, peak, baseline):
    return [row(study_id=study, record_id=record, ability_id=ability, design="case_report", population="synthetic single adult",
                n_total=1, condition_label="intervention", n_condition=1, lever_type=lever, outcome_measure=outcome,
                instrument="synthetic thermometer", unit=unit, timepoint="peak during session", stat_type="max_individual",
                value=peak, dispersion_type="none", baseline_value=baseline, is_primary_outcome="yes", value_source="text",
                **prov(study, 5))]


def write(path, header, rows):
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=header, lineterminator="\n")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


# ---- dry-run configuration: five abilities, k = 1 each ------------------------------------------------------------
dry = []
dry += rct_pair("synth_dry_rct_2001", "SYN-D1", "A14", "heart rate change on command", "bpm", "none",
                mean_i=4.1, sd_i=5.0, n_i=30, mean_c=0.6, sd_c=4.8, n_c=30)
dry += pre_post_row("synth_dry_prepost_2002", "SYN-D2", "A16", "systolic blood pressure", "mmHg", "breathing",
                    post=131.0, pre=138.5, sd_pre=12.0, n=24, r="")                       # pre_post_r blank -> placeholder
dry += crossover_pair("synth_dry_cross_2003", "SYN-D3", "A02", "left-right hand temperature difference", "degC",
                      "suggestion", mean_i=0.9, sd_i=0.6, mean_s=0.3, sd_s=0.5, n=18, r=0.6)
dry += prevalence_row("synth_dry_prev_2004", "SYN-D4", "A21", "able to move one ear", x=97, n=442)
dry += case_report_row("synth_dry_case_2005", "SYN-D5", "A03", "axillary temperature", "degC", "imagery",
                       peak=38.3, baseline=36.1)                                           # n = 1 -> Z via verified population SD
write(os.path.join(HERE, "master_dryrun.csv"), HEADER, dry)

# ---- pooling configuration ------------------------------------------------------------------------------------------
pool = []
# A03: k = 5 rct on axillary temperature (degC) -> SMD and Z (verified population SD row matches ability + unit)
a03 = [(0.9, 0.5, 22, 0.1, 0.5, 21), (1.2, 0.7, 15, 0.2, 0.6, 15), (0.6, 0.4, 40, 0.1, 0.4, 38),
       (1.5, 0.8, 12, 0.3, 0.7, 12), (0.8, 0.5, 26, 0.0, 0.5, 25)]
for j, (mi, si, ni, mc, sc, nc) in enumerate(a03, 1):
    disp = "SE" if j == 3 else "SD"                                    # one SE-reported pair
    pool += rct_pair(f"synth_a03_rct_{j:02d}", f"SYN-P03-{j}", "A03", "axillary temperature rise", "degC", "imagery",
                     mi, si, ni, mc, sc, nc, disp=disp)
# one non-primary outcome row pair for the first A03 study (reported individually, never pooled)
pool += rct_pair("synth_a03_rct_01", "SYN-P03-1", "A03", "finger temperature rise", "degC", "imagery",
                 2.1, 1.4, 22, 0.4, 1.3, 21, primary="no")
# A07: k = 4 pre_post finger warming, two with pre_post_r blank
a07 = [(33.9, 31.2, 1.9, 20, 0.55), (33.1, 31.5, 2.1, 16, ""), (34.2, 31.0, 1.7, 25, 0.62), (32.8, 31.4, 2.0, 14, "")]
for j, (post, pre, sd, n, r) in enumerate(a07, 1):
    pool += pre_post_row(f"synth_a07_pp_{j:02d}", f"SYN-P07-{j}", "A07", "finger skin temperature", "degC", "feedback",
                         post, pre, sd, n, r=r)
# A21: PLO k = 3
for j, (x, n) in enumerate([(97, 442), (41, 210), (120, 505)], 1):
    pool += prevalence_row(f"synth_a21_prev_{j:02d}", f"SYN-P21-{j}", "A21", "able to move one ear", x, n)
# A05: k = 12 rct HRV biofeedback (ms) for Egger / funnel; effects drawn around 0.5 SD with varying n
for j in range(1, 13):
    n_i = random.choice([10, 14, 20, 28, 36, 50]); n_c = n_i + random.choice([-2, 0, 2])
    sd = 12.0
    mi = round(random.gauss(6.0 + (3.0 if n_i <= 14 else 0.0), 2.5), 2)   # small studies slightly larger: asymmetry for Egger
    mc = round(random.gauss(0.5, 2.0), 2)
    pool += rct_pair(f"synth_a05_rct_{j:02d}", f"SYN-P05-{j}", "A05", "RMSSD change", "ms", "breathing",
                     mi, sd, n_i, mc, round(sd * random.uniform(0.9, 1.1), 1), n_c)
write(os.path.join(HERE, "master_pooling.csv"), HEADER, pool)

# ---- population SD: one verified synthetic row (A03 axillary temperature, degC) plus one unverified -------------------
pop_rows = [dict(ability_id="A03", variable="axillary temperature", mean=36.0, sd=0.48, unit="degC",
                 population="SYNTHETIC healthy adults", n=400, source_doi="10.0000/synthetic.popsd.a03",
                 source_citation="SYNTHETIC population SD row (make_synthetic_master.py)", location="SYNTHETIC",
                 status="verified", notes="synthetic; exercises the Z route only"),
            dict(ability_id="A14", variable="resting heart rate", mean=65.0, sd=8.0, unit="bpm",
                 population="SYNTHETIC adults", n="", source_doi="", source_citation="SYNTHETIC unverified row",
                 location="", status="pilot_unverified", notes="synthetic; must be ignored by 00_load.R")]
write(os.path.join(HERE, "population_sd_synthetic.csv"), POP_HEADER, pop_rows)

# ---- grade_final: contract item 6 header; outcome equals the primary row's outcome_measure --------------------------
grade_rows = []
for ab, outcome, k, n in [("A03", "axillary temperature rise", 5, 226), ("A07", "finger skin temperature", 4, 75),
                          ("A21", "able to move one ear", 3, 1157), ("A05", "RMSSD change", 12, 600)]:
    g = {h: "" for h in GRADE_HEADER}
    g.update(ability_id=ab, outcome=outcome, n_studies=k, n_participants=n, design_mix="SYNTHETIC", starting_level="High",
             rob_downgrade=0, inconsistency_downgrade=0, indirectness_downgrade=0, imprecision_downgrade=1,
             publication_bias_downgrade=0, large_effect_upgrade=0, dose_response_upgrade=0, opposing_confounding_upgrade=0,
             draft_certainty="Moderate", reasons="SYNTHETIC reasons text", plain_language_statement="SYNTHETIC statement",
             rater_id="synthetic-generator", date="2026-10-04", skill_version="synthetic0", model="synthetic-model-string",
             final_certainty="Moderate", final_rater_id="synthetic-nobody", final_date="2026-10-04",
             change_reason="", signed="no")
    grade_rows.append(g)
write(os.path.join(HERE, "grade_final_synthetic.csv"), GRADE_HEADER, grade_rows)
